/**
 * @fileoverview Auto-generated PagesCMS types from .pages.yml
 *
 * Generated by: scripts/generate-pages-cms-types.js
 * Do not edit manually - regenerate using: bun scripts/generate-pages-cms-types.js
 *
 * These types represent data validated by PagesCMS schema (.pages.yml).
 * Fields marked as required: true in the schema are non-optional.
 * Use these in JSDoc annotations to leverage validation guarantees.
 */

/**
 * @typedef {Object} PagesCMSEleventyNavigation
 * @property {string} ?key - 
 * @property {number} ?order - 
 */
export interface PagesCMSEleventyNavigation {
  key?: string;
  order?: number;
}

/**
 * @typedef {Object} PagesCMSFaq
 * @property {string} question - Question
 * @property {string} answer - Answer
 */
export interface PagesCMSFaq {
  question: string;
  answer: string;
}

/**
 * @typedef {Object} PagesCMSOption
 * @property {string} name - Option Name
 * @property {number} ?max_quantity - Max Quantity
 * @property {number} unit_price - Unit Price (£)
 * @property {number} ?days - Days (for hire products)
 */
export interface PagesCMSOption {
  name: string;
  max_quantity?: number;
  unit_price: number;
  days?: number;
}

/**
 * @typedef {Object} PagesCMSFilterAttribute
 * @property {string} name - Name
 * @property {string} value - Value
 */
export interface PagesCMSFilterAttribute {
  name: string;
  value: string;
}

/**
 * @typedef {Object} PagesCMSAddOnOption
 * @property {string} name - Name
 * @property {number} price - Price
 */
export interface PagesCMSAddOnOption {
  name: string;
  price: number;
}

/**
 * @typedef {Object} PagesCMSAddOn
 * @property {string} ?intro - Intro
 * @property {PagesCMSAddOnOption[]} ?options - Add-on Options
 */
export interface PagesCMSAddOn {
  intro?: string;
  options?: PagesCMSAddOnOption[];
}

/**
 * @typedef {Object} PagesCMSProduct
 * @property {string} ?product - Product
 */
export interface PagesCMSProduct {
  product?: string;
}

/**
 * @typedef {Object} PagesCMSOpeningTime
 * @property {string} day - Day
 * @property {string} hours - Hours
 */
export interface PagesCMSOpeningTime {
  day: string;
  hours: string;
}

/**
 * @typedef {Object} PagesCMSSocial
 * @property {string} ?Github - Github
 * @property {string} ?Forgejo - Forgejo
 * @property {string} ?Facebook - Facebook
 * @property {string} ?Instagram - Instagram
 * @property {string} ?TikTok - TikTok
 * @property {string} ?Google - Google
 * @property {string} ?WhatsApp - WhatsApp
 * @property {string} ?RSS - RSS
 */
export interface PagesCMSSocial {
  Github?: string;
  Forgejo?: string;
  Facebook?: string;
  Instagram?: string;
  TikTok?: string;
  Google?: string;
  WhatsApp?: string;
  RSS?: string;
}

/**
 * @typedef {Object} PagesCMSOrganizationFounder
 * @property {string} ?name - Name
 */
export interface PagesCMSOrganizationFounder {
  name?: string;
}

/**
 * @typedef {Object} PagesCMSOrganizationAddres
 * @property {string} ?streetAddress - Street Address
 * @property {string} ?addressLocality - City
 * @property {string} ?addressRegion - Region/State
 * @property {string} ?postalCode - Postal Code
 * @property {string} ?addressCountry - Country Code
 */
export interface PagesCMSOrganizationAddres {
  streetAddress?: string;
  addressLocality?: string;
  addressRegion?: string;
  postalCode?: string;
  addressCountry?: string;
}

/**
 * @typedef {Object} PagesCMSOrganizationContactPoint
 * @property {string} ?telephone - Telephone
 * @property {string} ?contactType - Contact Type
 * @property {string} ?areaServed - Area Served
 * @property {string} ?availableLanguage - Available Languages
 */
export interface PagesCMSOrganizationContactPoint {
  telephone?: string;
  contactType?: string;
  areaServed?: string;
  availableLanguage?: string;
}

/**
 * @typedef {Object} PagesCMSOrganization
 * @property {string} ?description - Organization Description
 * @property {string} ?legalName - Legal Name
 * @property {string} ?foundingDate - Founding Date
 * @property {PagesCMSOrganizationFounder[]} ?founders - Founders
 * @property {PagesCMSOrganizationAddres} ?address - Address
 * @property {PagesCMSOrganizationContactPoint[]} ?contactPoint - Contact Points
 */
export interface PagesCMSOrganization {
  description?: string;
  legalName?: string;
  foundingDate?: string;
  founders?: PagesCMSOrganizationFounder[];
  address?: PagesCMSOrganizationAddres;
  contactPoint?: PagesCMSOrganizationContactPoint[];
}

/**
 * @typedef {Object} PagesCMSImage
 * @property {string} ?path - Image
 * @property {string} ?alt - Alt Text
 */
export interface PagesCMSImage {
  path?: string;
  alt?: string;
}

